//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZotochkinaA_PR2_21._102.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collections
    {
        public Collections()
        {
            this.Products = new HashSet<Products>();
            this.Sales = new HashSet<Sales>();
        }
    
        public int IDCollection { get; set; }
        public string CollectionName { get; set; }
        public int CollectionNumber { get; set; }
        public int NumberOfProductsInCollection { get; set; }
        public int YearOfRealizeTheCollection { get; set; }
    
        public virtual ICollection<Products> Products { get; set; }
        public virtual ICollection<Sales> Sales { get; set; }
    }
}
