//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZotochkinaA_PR2_21._102.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Defects
    {
        public int IDDefectsProducts { get; set; }
        public int IDProduct { get; set; }
        public string DescriptionOfDefect { get; set; }
        public string Cause { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
