//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZotochkinaA_PR2_21._102.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        public Materials()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int IDMaterial { get; set; }
        public int IDSupplier { get; set; }
        public string MaterialName { get; set; }
        public decimal MaterialCosts { get; set; }
    
        public virtual Suppliers Suppliers { get; set; }
        public virtual ICollection<Products> Products { get; set; }
    }
}
