//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZotochkinaA_PR2_21._102.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.Defects = new HashSet<Defects>();
        }
    
        public int IDProduct { get; set; }
        public int IDSeason { get; set; }
        public int IDMaterial { get; set; }
        public int IDCollection { get; set; }
        public string ProductName { get; set; }
        public System.DateTime DateOfRealise { get; set; }
        public decimal ProductPrice { get; set; }
    
        public virtual Collections Collections { get; set; }
        public virtual ICollection<Defects> Defects { get; set; }
        public virtual Materials Materials { get; set; }
        public virtual Seasons Seasons { get; set; }
    }
}
