//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZotochkinaA_PR2_21._102.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int IDSales { get; set; }
        public int IDStore { get; set; }
        public int IDCollection { get; set; }
    
        public virtual Collections Collections { get; set; }
        public virtual Stores Stores { get; set; }
    }
}
