//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZotochkinaA_PR2_21._102.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seasons
    {
        public Seasons()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int IDSeason { get; set; }
        public string SeasonName { get; set; }
        public System.DateTime DateOfStartTheSeason { get; set; }
        public System.DateTime DateOfFinishTheSeason { get; set; }
    
        public virtual ICollection<Products> Products { get; set; }
    }
}
