//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZotochkinaA_PR2_21._102.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxAuthorities
    {
        public int IDTaxAuthority { get; set; }
        public Nullable<int> TaxAuthorityUniqueNumber { get; set; }
        public Nullable<System.DateTime> TaxAuthorityDate { get; set; }
        public Nullable<decimal> TaxAuthorityPrice { get; set; }
        public Nullable<int> IDStore { get; set; }
    
        public virtual Stores Stores { get; set; }
    }
}
