//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZotochkinaA_PR2_21._102.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workers
    {
        public string WorkerName { get; set; }
        public string WorkerSurname { get; set; }
        public string WorkerPatronymic { get; set; }
        public string PhoneNumber { get; set; }
        public string SeriePass { get; set; }
        public string NumberPass { get; set; }
        public int IDWorker { get; set; }
        public Nullable<int> IDUser { get; set; }
        public Nullable<int> TwoFactorAuth { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
